{
 "title": "sentiment Analysis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "sentiment_rows_processed_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sentiment_rows_processed_total",
     "legendFormat": "{{sentiment_processing_seconds}}"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sentiment_positive_total",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sentiment_positive_total)", "legendFormat": "__auto" },
    { "expr": "sum(sentiment_neutral_total)", "legendFormat": "__auto" },
    { "expr": "sum(sentiment_negative_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sentiment_positive_total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sentiment_positive_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sentiment_neutral_total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sentiment_neutral_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sentiment_negative_total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sentiment_negative_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}